FROM node:20

WORKDIR /app

COPY . .

RUN npm install --workspaces --include-workspace-root

ENV NODE_ENV=production
ENV PORT=3001

RUN npm run build

EXPOSE 3001

CMD ["npm", "run", "start:storefront"]