FROM node:20

WORKDIR /app

COPY . .

RUN npm install --workspaces --include-workspace-root

ENV NODE_ENV=production
ENV PORT=3000

RUN npm run build -w server

EXPOSE 3000

CMD ["npm", "run", "start:server"]