FROM node:20

WORKDIR /app

COPY . .

RUN npm install --workspaces --include-workspace-root

ENV NODE_ENV=production
ENV PORT=3001
ENV NEXT_PUBLIC_VENDURE_SHOP_API_URL=http://localhost:3000/shop-api

RUN npm run build

EXPOSE 3001

CMD ["npm", "run", "start:storefront"]