FROM node:20

WORKDIR /app

COPY . .

RUN npm install --workspaces --include-workspace-root

ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_PUBLIC_VENDURE_SHOP_API_URL=http://localhost:3000/shop-api
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:server"]